### ISSUE TITLE
change oauth2 redirect_uri to use https

### ISSUE THREAD

**Issue by thatbudakguy** [watzek/walklc#33]
adding an 's' manually in the URL bar fixed this for me

**Comment by rishijavia** [comment]
On Heroku it's a browser problem. The redirect URI on the Dev Website is set to use `https`

**Comment by thatbudakguy** [comment]
how do we fix it then? still not working in any browser unless I add the 's'

**Comment by rishijavia** [comment]
access the app using `https` therefore the URL will be `https://walklc.herokuapp.com`. I think changing it back to `http` is not using the "free" security certs provided by Heroku

**Comment by thatbudakguy** [comment]
ok, sounds good
