### ISSUE TITLE
manually requesting end date of a finished event shows 0 steps for all users

### ISSUE THREAD

**Issue by thatbudakguy** [watzek/walklc#61]
if you visit a finished event, the daily steps per user on the final day will render correctly, But, if you use the datepicker to manually select the final day, they'll all show as zeroes.

**Comment by rishijavia** [comment]
@thatbudakguy I cannot reproduce this bug. Please let me know if this bug is still persistent?

**Comment by thatbudakguy** [comment]
yep, seems fixed. closing
